import { ProjectSession, Epic, Story, ClarificationQuestion, PRDSection, ExportPackage } from './types';

export const mockSession: ProjectSession = {
  id: 'session-1',
  name: 'Team Access Management',
  inputType: 'Rough idea',
  outputDepth: 'Standard',
  jiraKey: 'TAM',
  targetUsers: ['Admin', 'Manager', 'Member'],
  businessGoal: 'Allow admins to invite and manage team members securely with role-based access control.',
  knownConstraints: 'Must integrate with existing RBAC system. Email invitations only (no SSO in v1).',
  labels: ['Auth', 'Security', 'RBAC'],
  rawInput: 'We need users to invite team members to projects, assign roles, and manage access. Admins should be able to remove users. Some roles should only view data. Need to support email invites and handle expired invitations.',
  currentPhase: 'stories',
  phases: {
    intake: 'complete',
    clarification: 'complete',
    prd: 'complete',
    epics: 'complete',
    stories: 'in-progress',
    quality: 'not-started',
    devReview: 'not-started',
    export: 'not-started'
  },
  createdAt: '2024-01-15T10:00:00Z',
  updatedAt: '2024-01-15T14:30:00Z',
};

export const mockSession2: ProjectSession = {
  id: 'session-2',
  name: 'Subscription Cancellation Flow',
  inputType: 'Meeting notes',
  outputDepth: 'Detailed',
  jiraKey: 'SUB',
  targetUsers: ['End user', 'Customer success'],
  businessGoal: 'Reduce churn by offering a smooth, friction-reduced cancellation flow with retention offers.',
  knownConstraints: 'Must comply with EU consumer rights regulations. Stripe integration required.',
  labels: ['Billing', 'Retention'],
  rawInput: 'Users need to cancel subscriptions. We need to show retention offers. CS team wants visibility. Legal says we need to comply with EU regulations for subscription cancellation.',
  currentPhase: 'epics',
  phases: {
    intake: 'complete',
    clarification: 'complete',
    prd: 'complete',
    epics: 'in-progress',
    stories: 'not-started',
    quality: 'not-started',
    devReview: 'not-started',
    export: 'not-started'
  },
  createdAt: '2024-01-14T09:00:00Z',
  updatedAt: '2024-01-15T11:00:00Z',
};

export const mockSession3: ProjectSession = {
  id: 'session-3',
  name: 'Multi-language Checkout',
  inputType: 'Stakeholder request',
  outputDepth: 'Standard',
  jiraKey: 'I18N',
  targetUsers: ['International customers'],
  businessGoal: 'Support checkout in 8 languages to expand into EU and APAC markets.',
  knownConstraints: 'Currency conversion handled by payment provider. RTL languages in scope.',
  labels: ['i18n', 'Checkout', 'Payments'],
  rawInput: 'We need to support multiple languages in checkout. Stakeholders want 8 languages. RTL support for Arabic and Hebrew. Currency should auto-convert.',
  currentPhase: 'clarification',
  phases: {
    intake: 'complete',
    clarification: 'in-progress',
    prd: 'not-started',
    epics: 'not-started',
    stories: 'not-started',
    quality: 'not-started',
    devReview: 'not-started',
    export: 'not-started'
  },
  createdAt: '2024-01-13T14:00:00Z',
  updatedAt: '2024-01-14T16:00:00Z',
};

export const mockSession4: ProjectSession = {
  id: 'session-4',
  name: 'Admin Reporting Dashboard',
  inputType: 'PRD draft',
  outputDepth: 'Detailed',
  jiraKey: 'RPT',
  targetUsers: ['Admin', 'Executive'],
  businessGoal: 'Give admins and executives real-time visibility into platform usage and revenue metrics.',
  knownConstraints: 'Data warehouse is BigQuery. Must not expose PII in reports.',
  labels: ['Analytics', 'Admin'],
  rawInput: 'We need a reporting dashboard for admins. Should show revenue, user growth, and feature adoption. Executives want weekly email digests too.',
  currentPhase: 'prd',
  phases: {
    intake: 'complete',
    clarification: 'complete',
    prd: 'in-progress',
    epics: 'not-started',
    stories: 'not-started',
    quality: 'not-started',
    devReview: 'not-started',
    export: 'not-started'
  },
  createdAt: '2024-01-12T11:00:00Z',
  updatedAt: '2024-01-13T15:00:00Z',
};

export const allSessions: ProjectSession[] = [mockSession, mockSession2, mockSession3, mockSession4];

export const mockClarificationQuestions: ClarificationQuestion[] = [
  // Business Goal
  { id: 'q1', group: 'Business Goal', text: 'What is the primary business objective of the access management system?', required: true, answer: 'To enable secure team collaboration by allowing admins to control who has access to what within the platform.', skipped: false },
  { id: 'q2', group: 'Business Goal', text: 'How does this feature contribute to revenue or retention?', required: true, answer: 'Reduces churn by enabling enterprise teams to onboard collaborators without IT friction.', skipped: false },
  { id: 'q3', group: 'Business Goal', text: 'What is the success metric — e.g., time-to-invite, invitation acceptance rate?', required: false, answer: 'Invitation acceptance rate > 80% within 48 hours. Zero unauthorized access incidents.', skipped: false },
  // Target Users
  { id: 'q4', group: 'Target Users / Personas', text: 'Who are the primary users of the invitation flow — admins, managers, or both?', required: true, answer: 'Admins primarily. Managers can invite within their own team scope.', skipped: false },
  { id: 'q5', group: 'Target Users / Personas', text: 'Do invited users need to create an account, or can they use SSO?', required: true, answer: 'Create an account with email/password in v1. SSO planned for v2.', skipped: false },
  { id: 'q6', group: 'Target Users / Personas', text: 'Are there external (guest) users, or only internal team members?', required: false, answer: 'Internal team members only in v1. Guest access is out of scope.', skipped: false },
  // Scope
  { id: 'q7', group: 'Scope & Non-Goals', text: 'What roles are in scope for v1? Should these be predefined or custom?', required: true, answer: 'Predefined roles: Admin, Manager, Member, Viewer. Custom roles are out of scope for v1.', skipped: false },
  { id: 'q8', group: 'Scope & Non-Goals', text: 'Is bulk invitation in scope (e.g., CSV import)?', required: false, answer: '', skipped: true },
  { id: 'q9', group: 'Scope & Non-Goals', text: 'Can users belong to multiple teams/projects simultaneously?', required: true, answer: 'Yes, users can be members of multiple projects with different roles per project.', skipped: false },
  // UX/Design
  { id: 'q10', group: 'UX / Design Needs', text: 'Should invitation acceptance be a dedicated page, or inline in the app?', required: true, answer: 'Dedicated landing page for invitation acceptance with a clear CTA.', skipped: false },
  { id: 'q11', group: 'UX / Design Needs', text: 'What should happen if a user tries to invite someone who already has an account?', required: true, answer: 'Show a warning and allow the admin to add them to the project directly without sending an email.', skipped: false },
  // Edge Cases
  { id: 'q12', group: 'Edge Cases', text: 'What happens when an invitation link expires?', required: true, answer: 'Show a clear error page with an option to request a new link. Expiry is 72 hours.', skipped: false },
  { id: 'q13', group: 'Edge Cases', text: 'Can the same email be invited multiple times in parallel?', required: false, answer: 'No. System should detect duplicate pending invitations and prompt admin to resend instead.', skipped: false },
  // Error Handling
  { id: 'q14', group: 'Error Handling', text: 'What error states should the invitation form handle?', required: true, answer: 'Invalid email format, duplicate invitation, email delivery failure, role selection required.', skipped: false },
  { id: 'q15', group: 'Error Handling', text: 'What happens if a user is removed while they are actively using the platform?', required: true, answer: 'Their session is invalidated immediately. They see a friendly "access revoked" message.', skipped: false },
  // Localization
  { id: 'q16', group: 'Localization', text: 'Does the invitation email need to be localized?', required: false, answer: 'Email should use the invitee\'s language preference if known, otherwise default to English.', skipped: false },
  // Technical
  { id: 'q17', group: 'Technical Constraints', text: 'What email service is being used, and are there rate limits on invitations?', required: true, answer: 'SendGrid. Rate limit: 50 invitations per admin per hour.', skipped: false },
  { id: 'q18', group: 'Technical Constraints', text: 'Should invitation tokens be single-use or reusable until expiry?', required: true, answer: 'Single-use. Once accepted, the token is invalidated.', skipped: false },
  // Dependencies
  { id: 'q19', group: 'Dependencies', text: 'Does this require changes to the existing RBAC service or authentication layer?', required: true, answer: 'Yes. RBAC service team (Backend squad) needs to expose role assignment API endpoints.', skipped: false },
  { id: 'q20', group: 'Dependencies', text: 'Is there a design system component library that email templates should use?', required: false, answer: 'Yes, use the existing branded email templates from the Design team.', skipped: false },
  // Analytics
  { id: 'q21', group: 'Analytics / Tracking', text: 'What events should be tracked for this feature?', required: false, answer: 'invitation_sent, invitation_accepted, invitation_expired, role_changed, member_removed', skipped: false },
  // Risks
  { id: 'q22', group: 'Risks', text: 'What are the security risks of the invitation system?', required: true, answer: 'Token hijacking, brute-force on invitation URLs. Mitigate with UUID tokens, rate limiting, and HTTPS-only links.', skipped: false },
];

export const mockPRDSections: PRDSection[] = [
  { id: 'prd-1', title: 'Summary', content: 'A secure team access management system enabling admins to invite members, assign roles, and manage permissions. The system supports email-based invitations with configurable expiry, role-based access control with four predefined roles, and a management interface for ongoing team administration.', complete: true, order: 1 },
  { id: 'prd-2', title: 'Problem Statement', content: 'Teams scaling beyond 10 members face friction when onboarding collaborators. Current process requires manual DB changes by engineers, causing 3-5 day delays per new member. Unauthorized access has occurred twice in Q4 due to lack of proper offboarding workflows. This blocks enterprise sales deals that require role-based access control.', complete: true, order: 2 },
  { id: 'prd-3', title: 'Goals', content: '• Reduce time-to-invite from 3 days to under 5 minutes\n• Achieve 80%+ invitation acceptance rate within 48 hours\n• Zero unauthorized access incidents post-launch\n• Enable enterprise tier feature gate for access management\n• Reduce support tickets related to member access by 60%', complete: true, order: 3 },
  { id: 'prd-4', title: 'Non-Goals', content: '• Custom role creation (v2)\n• SSO / SAML integration (v2)\n• Guest / external user access (v2)\n• Bulk CSV invitation import (v2)\n• Slack/Teams integration for invitation delivery (v2)\n• Granular permission overrides per resource (v2)', complete: true, order: 4 },
  { id: 'prd-5', title: 'Target Users / Personas', content: '**Admin (Primary):** Workspace owner with full access. Manages all members, roles, and billing.\n\n**Manager:** Can invite members within their team. Cannot remove other managers or admins.\n\n**Member:** Standard collaborator. Read/write access to assigned projects.\n\n**Viewer:** Read-only access to assigned projects. Cannot create or modify content.', complete: true, order: 5 },
  { id: 'prd-6', title: 'User Journeys', content: '**Journey 1 — Invite a new member:**\nAdmin opens Members page → Clicks "Invite Member" → Enters email, selects role → Sends invitation → Member receives email, clicks link → Member creates account or logs in → Member is added to workspace.\n\n**Journey 2 — Manage existing member:**\nAdmin opens Members page → Finds member → Changes role or removes → Changes take effect immediately.\n\n**Journey 3 — Handle expired invitation:**\nMember clicks expired link → Sees clear error message → Requests new link → Admin receives notification → Resends invitation.', complete: true, order: 6 },
  { id: 'prd-7', title: 'Functional Requirements', content: 'FR-1: Admin can invite a user by email address\nFR-2: Admin can assign one of four predefined roles during invitation\nFR-3: System sends a branded invitation email with a unique expiring link (72h)\nFR-4: Invitee can accept invitation and create account or link existing account\nFR-5: Admin can view all pending and active invitations\nFR-6: Admin can resend or revoke a pending invitation\nFR-7: Admin can view all team members and their roles\nFR-8: Admin can change a member\'s role at any time\nFR-9: Admin can remove a member, immediately revoking their access\nFR-10: System invalidates session immediately upon member removal\nFR-11: Rate limit: 50 invitations per admin per hour via SendGrid\nFR-12: System detects duplicate pending invitations and prevents re-invite', complete: true, order: 7 },
  { id: 'prd-8', title: 'Non-Functional Requirements', content: '• Invitation email delivery: < 30 seconds p95\n• Invitation acceptance page load: < 1.5s\n• Session revocation: < 2 seconds from removal action\n• 99.9% uptime SLA for invitation service\n• HTTPS-only invitation links\n• UUID v4 tokens (min 128-bit entropy)\n• Audit log retention: 12 months\n• GDPR-compliant: invitee email deleted if invitation not accepted after 90 days', complete: true, order: 8 },
  { id: 'prd-9', title: 'Assumptions', content: '• Users have a valid email address\n• SendGrid account is provisioned and email templates are ready\n• RBAC service exposes role assignment endpoints by launch date\n• Only one workspace per account in v1 (multi-workspace in roadmap)\n• Invitations require account creation; no magic-link passwordless access', complete: true, order: 9 },
  { id: 'prd-10', title: 'Risks', content: '• Email deliverability (spam filters): Mitigate with SendGrid reputation management and SPF/DKIM setup\n• Token security: UUID v4 + rate limiting + HTTPS-only\n• RBAC service dependency: Risk of delay if backend squad is unavailable\n• Scope creep from stakeholders wanting SSO in v1: Communicate firm v2 boundary\n• Session invalidation race conditions: Require atomic DB update + cache invalidation', complete: true, order: 10 },
  { id: 'prd-11', title: 'Success Metrics', content: '• Time-to-invite: < 5 minutes (target)\n• Invitation acceptance rate: ≥ 80% within 48 hours\n• Unauthorized access incidents: 0 in first 90 days\n• Support tickets for member access: ↓ 60% vs baseline\n• Enterprise deals unblocked by RBAC: Track in CRM\n• NPS from admins specifically: > 40', complete: true, order: 11 },
  { id: 'prd-12', title: 'Open Questions', content: '• Q: Should managers be able to invite other managers?\n  Status: Pending design decision\n\n• Q: What is the UX for the "request new link" flow — in-app or via email support?\n  Status: Needs input from CS team\n\n• Q: Should we notify the admin when an invitation expires?\n  Status: Nice-to-have, TBD', complete: false, order: 12 },
];

export const mockEpics: Epic[] = [
  {
    id: 'epic-1',
    sessionId: 'session-1',
    title: 'Team Invitation Management',
    businessObjective: 'Enable admins to securely invite new team members via email, reducing onboarding from days to minutes.',
    scopeSummary: 'Email invitation form, SendGrid integration, invitation tracking dashboard, accept/decline flows.',
    prdRequirements: ['FR-1', 'FR-2', 'FR-3', 'FR-4', 'FR-5', 'FR-6'],
    priority: 'P0',
    dependencies: ['Backend RBAC API', 'SendGrid setup', 'Email template design'],
    risks: ['Email deliverability', 'SendGrid rate limits'],
    jiraEpicDescription: 'Enable admins to invite team members via email with role assignment. Covers the full invitation lifecycle: send, track, accept, resend, and revoke.\n\nAcceptance: Admin can send, track, and manage invitations end-to-end. Invitee can accept and onboard in < 5 minutes.',
    storyCount: 4
  },
  {
    id: 'epic-2',
    sessionId: 'session-1',
    title: 'Role-Based Access Control',
    businessObjective: 'Implement four predefined roles (Admin, Manager, Member, Viewer) to secure access to platform resources.',
    scopeSummary: 'Role model enforcement, role display in UI, role validation on API, permissions matrix.',
    prdRequirements: ['FR-2', 'FR-8', 'FR-9'],
    priority: 'P0',
    dependencies: ['RBAC service API (backend squad)', 'Auth middleware'],
    risks: ['RBAC service delivery delay', 'Permission edge cases with multi-project membership'],
    jiraEpicDescription: 'Define and enforce four predefined roles across all platform resources. Role changes must take effect immediately.\n\nAcceptance: Each role has correct permissions across all resource types. Role change is reflected within 2 seconds.',
    storyCount: 3
  },
  {
    id: 'epic-3',
    sessionId: 'session-1',
    title: 'Member Administration',
    businessObjective: 'Give admins a clear interface to view, manage, and offboard team members at any time.',
    scopeSummary: 'Members list view, role change UI, member removal with session invalidation, audit log.',
    prdRequirements: ['FR-7', 'FR-8', 'FR-9', 'FR-10'],
    priority: 'P1',
    dependencies: ['Epic 1 (invitation)', 'Epic 2 (RBAC)', 'Session management service'],
    risks: ['Session invalidation race condition'],
    jiraEpicDescription: 'Admin interface for viewing all workspace members, changing their roles, and removing them. Removal must invalidate sessions immediately.\n\nAcceptance: Admin can manage all members. Removed member loses access within 2 seconds.',
    storyCount: 3
  },
  {
    id: 'epic-4',
    sessionId: 'session-1',
    title: 'Invitation Lifecycle & Error Handling',
    businessObjective: 'Ensure robust handling of invitation edge cases: expiry, duplicate invites, rate limiting, and error states.',
    scopeSummary: 'Token expiry UI, request-new-link flow, duplicate detection, rate limit messaging, audit trail.',
    prdRequirements: ['FR-11', 'FR-12'],
    priority: 'P1',
    dependencies: ['Epic 1 (invitation)', 'Email service'],
    risks: ['Complexity of expiry UX', 'Rate limit edge cases during bulk onboarding'],
    jiraEpicDescription: 'Handle all edge cases in the invitation lifecycle: expired tokens, duplicate invitations, rate limiting, and error recovery flows.\n\nAcceptance: All error states show clear, actionable messaging. No silent failures.',
    storyCount: 2
  },
];

export const mockStories: Story[] = [
  // Epic 1: Team Invitation Management
  {
    id: 'TAM-001',
    epicId: 'epic-1',
    sessionId: 'session-1',
    title: 'Invite team member by email',
    userStory: 'As an Admin, I want to invite a team member by email address, so that they can join the workspace with the appropriate role.',
    description: 'A modal or dedicated form enabling admins to enter an email address, select a role, and send an invitation. The form validates the email, checks for existing accounts and pending invitations, then dispatches the invitation via SendGrid.',
    acceptanceCriteria: [
      'Admin can open invitation form from the Members page via "Invite Member" button.',
      'Form requires a valid email address (format validation inline).',
      'Role selector shows all four roles with brief descriptions.',
      'Submitting the form sends an invitation email via SendGrid within 30 seconds.',
      'Admin sees a success toast: "Invitation sent to [email]".',
      'Invitation appears in the pending invitations list immediately after send.',
      'Form disables submit button while request is in flight.',
    ],
    priority: 'P0',
    labels: ['Auth', 'Invitation'],
    components: ['Frontend', 'Backend', 'Email'],
    dependencies: ['SendGrid integration', 'RBAC role list API'],
    edgeCases: [
      'Email is already registered as a workspace member → Show warning, do not send.',
      'Email has a pending invitation → Prompt admin to resend instead.',
      'Invalid email format → Inline validation before submit.',
      'Role not selected → Prevent submission with validation message.',
    ],
    errorHandling: 'Email delivery failure: Show error toast with retry option. Server error: Show generic error with support link. Rate limit hit: Show "You\'ve reached the invitation limit (50/hour). Try again in X minutes."',
    localizationNotes: 'Invitation email content must be sent in invitee\'s preferred language (default: English). Form UI is in workspace locale.',
    designNotes: 'Modal overlay on Members page. Role selector should show role name + 1-line description. Confirm button should be primary/filled. Consider a role comparison tooltip.',
    analyticsNotes: 'Track: invitation_form_opened, invitation_sent (role, existing_user: bool), invitation_send_failed',
    qaNotes: 'Test with: valid new email, existing member email, pending invite email, invalid format. Test SendGrid failure simulation. Test rate limit boundary.',
    technicalNotes: 'POST /api/invitations. Token: UUID v4, expires 72h. Store: invitations table (email, token_hash, role, expires_at, status). Use SendGrid transactional template ID.',
    openQuestions: ['What is the default role when no role is selected — should there be a default, or force selection?'],
    readinessScore: {
      total: 88,
      clarity: 18,
      acceptanceCriteria: 18,
      businessAlignment: 13,
      technicalFeasibility: 13,
      testability: 9,
      edgeCasesErrorHandling: 9,
      dependenciesDesignLocalization: 8,
      label: 'Minor review needed'
    },
    warnings: [
      { id: 'w1', type: 'missing-analytics', message: 'Analytics events defined but not mapped to implementation', severity: 'info' }
    ],
    reviewStatus: 'approved',
    developerReview: {
      status: 'approved',
      comment: 'Clear and ready. SendGrid template ID needs to be confirmed with the email team before implementation.',
      reviewerName: 'Sasha K.',
      timestamp: '2024-01-15T12:00:00Z',
      pmRevisionStatus: 'resolved'
    }
  },
  {
    id: 'TAM-002',
    epicId: 'epic-1',
    sessionId: 'session-1',
    title: 'Assign role during invitation',
    userStory: 'As an Admin, I want to assign a role when inviting a member, so that their access is correctly scoped from day one.',
    description: 'Role selection is part of the invitation form. Admin selects one of four predefined roles (Admin, Manager, Member, Viewer). The selected role is stored with the invitation and applied when the invitee accepts.',
    acceptanceCriteria: [
      'Role selector displays four options: Admin, Manager, Member, Viewer.',
      'Each role shows a brief description (1 line) to guide selection.',
      'Selected role is applied to the user\'s account upon invitation acceptance.',
      'Role is visible in the pending invitations list.',
      'Admin can change role on a pending invitation before it is accepted.',
    ],
    priority: 'P0',
    labels: ['Auth', 'RBAC'],
    components: ['Frontend', 'Backend'],
    dependencies: ['TAM-001 (invite form)', 'RBAC role list API'],
    edgeCases: [
      'Admin tries to assign "Admin" role — show confirmation dialog.',
      'Role list fails to load — disable form with error state.',
    ],
    errorHandling: 'If RBAC API fails to load roles, show inline error with retry. Block submission until roles are loaded.',
    localizationNotes: 'Role names and descriptions should use translation keys.',
    designNotes: 'Role selector as a radio group with role name + description. Admin role should have a warning callout (high privilege).',
    analyticsNotes: 'Track: role_selected (role_name) on invitation form.',
    qaNotes: 'Verify each role type is correctly stored and applied post-acceptance. Test Admin role confirmation dialog.',
    technicalNotes: 'Roles sourced from GET /api/rbac/roles. Role ID stored in invitations.role_id.',
    openQuestions: [],
    readinessScore: {
      total: 82,
      clarity: 17,
      acceptanceCriteria: 16,
      businessAlignment: 13,
      technicalFeasibility: 12,
      testability: 8,
      edgeCasesErrorHandling: 8,
      dependenciesDesignLocalization: 8,
      label: 'Minor review needed'
    },
    warnings: [],
    reviewStatus: 'pending'
  },
  {
    id: 'TAM-003',
    epicId: 'epic-1',
    sessionId: 'session-1',
    title: 'Accept invitation via email link',
    userStory: 'As an invited user, I want to click the invitation link in my email, so that I can join the workspace quickly.',
    description: 'Clicking the invitation link takes the user to an acceptance page. If they have an existing account, they log in and are added to the workspace. If not, they complete account creation. The token is validated and the invitation is marked as accepted.',
    acceptanceCriteria: [
      'Clicking the invitation link opens the acceptance page with workspace branding.',
      'Page validates the token and shows an error if expired or already used.',
      'Existing users can log in to accept; new users see account creation form.',
      'After acceptance, user is added to workspace with the correct role.',
      'User is redirected to the workspace dashboard post-acceptance.',
      'Invitation token is invalidated (single-use) after acceptance.',
    ],
    priority: 'P0',
    labels: ['Auth', 'Onboarding'],
    components: ['Frontend', 'Backend'],
    dependencies: ['TAM-001', 'Auth service'],
    edgeCases: [
      'Token expired → Show expiry message with "Request new link" CTA.',
      'Token already used → Show "Already accepted" message.',
      'User is already a workspace member → Skip acceptance, redirect to dashboard.',
    ],
    errorHandling: 'Token validation failure: Show clear error with reason and support link. Network failure: Retry with exponential backoff. Account creation errors: Inline form validation.',
    localizationNotes: 'Acceptance page should use invitee\'s browser language or stored language preference.',
    designNotes: 'Acceptance page is a standalone landing page (not in main app shell). Show workspace logo, invitation details, and clear CTA. Mobile-optimized.',
    analyticsNotes: 'Track: invitation_link_clicked, invitation_accepted, invitation_already_used, new_account_created',
    qaNotes: 'Test: valid token, expired token, used token, existing user, new user. Test mobile viewport.',
    technicalNotes: 'GET /api/invitations/:token — validate and return invitation details. POST /api/invitations/:token/accept — mark accepted, create workspace membership. JWT issued post-acceptance.',
    openQuestions: ['Should the acceptance page be branded per workspace or generic platform branding?'],
    readinessScore: {
      total: 91,
      clarity: 19,
      acceptanceCriteria: 19,
      businessAlignment: 14,
      technicalFeasibility: 14,
      testability: 9,
      edgeCasesErrorHandling: 9,
      dependenciesDesignLocalization: 7,
      label: 'Ready for Jira'
    },
    warnings: [],
    reviewStatus: 'approved',
    developerReview: {
      status: 'approved',
      comment: 'Good coverage. The single-use token invalidation needs to be atomic to prevent race conditions on double-click.',
      reviewerName: 'Priya M.',
      timestamp: '2024-01-15T13:00:00Z',
      pmRevisionStatus: 'resolved'
    }
  },
  {
    id: 'TAM-004',
    epicId: 'epic-1',
    sessionId: 'session-1',
    title: 'Resend or revoke pending invitation',
    userStory: 'As an Admin, I want to resend or revoke a pending invitation, so that I can correct mistakes and manage invite lifecycle.',
    description: 'In the pending invitations list, admin can resend an invitation (generates a new token, resets expiry) or revoke it (marks as revoked, invalidates token). Actions are accessible via a contextual menu or action buttons on each invitation row.',
    acceptanceCriteria: [
      'Admin can see all pending invitations in a table with email, role, sent date, and expiry.',
      '"Resend" action generates a new token, resets expiry, sends new email, and updates sent date.',
      '"Revoke" action marks invitation as revoked, prevents acceptance, and confirms via dialog.',
      'Revoked invitations show "Revoked" status in the table.',
      'Resending a revoked invitation is not possible.',
    ],
    priority: 'P1',
    labels: ['Auth', 'Invitation'],
    components: ['Frontend', 'Backend'],
    dependencies: ['TAM-001'],
    edgeCases: [
      'Resending when rate limit is hit → Show rate limit message.',
      'Revoking an invitation that was just accepted (race condition) → Show "Already accepted" error.',
    ],
    errorHandling: 'Resend failure: Show error toast. Revoke failure: Show error toast, do not update UI state.',
    localizationNotes: 'Resent email uses same localization as original invitation.',
    designNotes: 'Action dropdown per invitation row. Revoke requires confirmation dialog to prevent accidental revocation.',
    analyticsNotes: 'Track: invitation_resent, invitation_revoked',
    qaNotes: 'Test resend: new token generated, old token invalidated, new email sent. Test revoke: token invalid, user cannot accept.',
    technicalNotes: 'PUT /api/invitations/:id/resend. DELETE /api/invitations/:id. Old token must be invalidated synchronously on resend.',
    openQuestions: [],
    readinessScore: {
      total: 78,
      clarity: 16,
      acceptanceCriteria: 15,
      businessAlignment: 12,
      technicalFeasibility: 12,
      testability: 8,
      edgeCasesErrorHandling: 8,
      dependenciesDesignLocalization: 7,
      label: 'Minor review needed'
    },
    warnings: [
      { id: 'w2', type: 'edge-cases', message: 'Race condition on revoke/accept not fully specified', severity: 'warning' }
    ],
    reviewStatus: 'needs-clarification',
    developerReview: {
      status: 'needs-clarification',
      comment: 'Need to clarify: when resending, is the old token immediately invalidated server-side before new one is generated, or is there a window?',
      reviewerName: 'Sasha K.',
      timestamp: '2024-01-15T14:00:00Z',
      pmRevisionStatus: 'in-progress'
    }
  },
  // Epic 2: Role-Based Access Control
  {
    id: 'TAM-005',
    epicId: 'epic-2',
    sessionId: 'session-1',
    title: 'Enforce role permissions across platform resources',
    userStory: 'As a Viewer, I want my access to be limited to read-only actions, so that I cannot accidentally modify workspace content.',
    description: 'The platform enforces permissions based on the user\'s role at both the UI level (hiding/disabling unauthorized actions) and the API level (returning 403 for unauthorized requests). Permissions matrix: Admin (full), Manager (create/edit, no billing), Member (create/edit own), Viewer (read-only).',
    acceptanceCriteria: [
      'Admin has unrestricted access to all resources.',
      'Manager cannot access billing or workspace settings.',
      'Member cannot edit or delete content owned by other members.',
      'Viewer sees no create/edit/delete actions in the UI.',
      'API returns 403 for unauthorized actions regardless of UI state.',
      'Role permissions are checked server-side, not only in frontend.',
    ],
    priority: 'P0',
    labels: ['RBAC', 'Security'],
    components: ['Frontend', 'Backend', 'Auth middleware'],
    dependencies: ['RBAC service API', 'Auth middleware'],
    edgeCases: [
      'User\'s role is changed mid-session → Apply on next API request, not live.',
      'Viewer tries to access a create endpoint directly via API → 403.',
    ],
    errorHandling: '403 responses: Show "Access denied" in UI. Do not reveal why access was denied beyond role mismatch.',
    localizationNotes: 'Access denied messages should be localized.',
    designNotes: 'Hide unauthorized actions rather than disable with tooltip where possible to reduce noise. Use "disabled + tooltip" only for upgrade prompts.',
    analyticsNotes: 'Track: unauthorized_access_attempt (role, resource, action)',
    qaNotes: 'Full permission matrix testing required. Test each role against each resource type. Include API-level testing bypassing UI.',
    technicalNotes: 'Middleware: role permission check before route handler. Use canPerform(user.role, resource, action) utility. Store permissions matrix in config, not DB.',
    openQuestions: ['Is Manager role able to change Member roles, or is that Admin-only?'],
    readinessScore: {
      total: 74,
      clarity: 14,
      acceptanceCriteria: 16,
      businessAlignment: 13,
      technicalFeasibility: 11,
      testability: 8,
      edgeCasesErrorHandling: 7,
      dependenciesDesignLocalization: 5,
      label: 'Needs PM refinement'
    },
    warnings: [
      { id: 'w3', type: 'missing-ac', message: 'Permissions matrix not fully enumerated in acceptance criteria', severity: 'error' },
      { id: 'w4', type: 'technical-dependency', message: 'Hidden dependency: RBAC service API contract not yet agreed', severity: 'warning' },
    ],
    reviewStatus: 'technically-risky',
    developerReview: {
      status: 'technically-risky',
      comment: 'The permissions matrix needs to be fully defined before implementation. "Member cannot edit content owned by other members" requires ownership tracking which is not in the data model yet.',
      reviewerName: 'Jordan L.',
      timestamp: '2024-01-15T15:00:00Z',
      pmRevisionStatus: 'not-started'
    }
  },
  {
    id: 'TAM-006',
    epicId: 'epic-2',
    sessionId: 'session-1',
    title: 'Display current role in user profile and member list',
    userStory: 'As any user, I want to see my current role clearly in my profile, so that I understand what I can and cannot do.',
    description: 'The user\'s role is displayed in: (1) the user profile/account page, (2) the members list as an admin, (3) the top nav or user avatar dropdown. Role is shown as a labeled badge.',
    acceptanceCriteria: [
      'User profile page shows current role as a badge.',
      'Members list shows each member\'s role.',
      'Role badge uses distinct colors per role (not color alone — also icon or label).',
      'Role label is human-readable (not an internal ID).',
    ],
    priority: 'P2',
    labels: ['UI', 'RBAC'],
    components: ['Frontend'],
    dependencies: ['TAM-005'],
    edgeCases: ['Role updated externally — UI should refresh on next page load.'],
    errorHandling: 'If role data fails to load, show a generic "Member" label as fallback.',
    localizationNotes: 'Role labels must use translation keys.',
    designNotes: 'Role badges: Admin (primary blue), Manager (purple), Member (gray), Viewer (light gray). Always include text label alongside color.',
    analyticsNotes: '',
    qaNotes: 'Verify all four roles display correctly. Test color contrast for accessibility.',
    technicalNotes: 'Role pulled from user session token claims. No additional API call needed.',
    openQuestions: [],
    readinessScore: {
      total: 86,
      clarity: 17,
      acceptanceCriteria: 17,
      businessAlignment: 13,
      technicalFeasibility: 14,
      testability: 9,
      edgeCasesErrorHandling: 8,
      dependenciesDesignLocalization: 8,
      label: 'Minor review needed'
    },
    warnings: [],
    reviewStatus: 'pending'
  },
  {
    id: 'TAM-007',
    epicId: 'epic-2',
    sessionId: 'session-1',
    title: 'Change member role',
    userStory: 'As an Admin, I want to change a team member\'s role, so that their access level reflects their current responsibilities.',
    description: 'From the Members list, an admin can change any member\'s role via an inline dropdown or edit action. The change is applied immediately and takes effect on the member\'s next API request.',
    acceptanceCriteria: [
      'Admin can change a member\'s role from the Members list.',
      'Role change requires confirmation for Admin role assignment.',
      'Change takes effect on the member\'s next API request (no force logout required).',
      'Admin sees a success toast on role change.',
      'Role change is recorded in the audit log.',
    ],
    priority: 'P1',
    labels: ['RBAC', 'Admin'],
    components: ['Frontend', 'Backend'],
    dependencies: ['RBAC service API', 'TAM-006'],
    edgeCases: [
      'Admin tries to demote themselves — show warning, require confirmation.',
      'Last Admin tries to remove Admin role — block action with error.',
    ],
    errorHandling: 'API failure on role change: Show error toast, revert UI to previous role.',
    localizationNotes: 'Confirmation and toast messages localized.',
    designNotes: 'Inline role dropdown on member row. Confirm dialog for Admin role changes. Smooth optimistic UI update.',
    analyticsNotes: 'Track: role_changed (from_role, to_role)',
    qaNotes: 'Test each role change permutation. Test self-demotion. Test last-admin protection.',
    technicalNotes: 'PATCH /api/workspace/members/:id. Invalidate permission cache for that user.',
    openQuestions: [],
    readinessScore: {
      total: 92,
      clarity: 19,
      acceptanceCriteria: 19,
      businessAlignment: 14,
      technicalFeasibility: 14,
      testability: 9,
      edgeCasesErrorHandling: 9,
      dependenciesDesignLocalization: 8,
      label: 'Ready for Jira'
    },
    warnings: [],
    reviewStatus: 'approved',
    developerReview: {
      status: 'approved',
      comment: 'Well specified. Ready.',
      reviewerName: 'Priya M.',
      timestamp: '2024-01-15T15:30:00Z',
      pmRevisionStatus: 'resolved'
    }
  },
  // Epic 3: Member Administration
  {
    id: 'TAM-008',
    epicId: 'epic-3',
    sessionId: 'session-1',
    title: 'View all workspace members',
    userStory: 'As an Admin, I want to see all workspace members in one place, so that I can manage the team efficiently.',
    description: 'A Members page accessible from the Settings or main navigation. Displays all active members in a table with name, email, role, join date, and last active date. Supports search and role filter.',
    acceptanceCriteria: [
      'Members page shows all active workspace members.',
      'Table columns: Name, Email, Role, Joined, Last Active, Actions.',
      'Admin can search members by name or email.',
      'Admin can filter by role.',
      'Pending invitations shown in a separate "Pending" tab.',
      'Table is sorted by join date descending by default.',
    ],
    priority: 'P1',
    labels: ['Admin', 'UI'],
    components: ['Frontend', 'Backend'],
    dependencies: ['TAM-007'],
    edgeCases: ['Empty state: no members beyond admin — show "Invite your first member" CTA.'],
    errorHandling: 'If member list fails to load, show error with retry.',
    localizationNotes: 'Date formats localized.',
    designNotes: 'Clean data table with tight row height. Role shown as badge. Actions column with dropdown: "Change Role", "Remove".',
    analyticsNotes: 'Track: members_page_viewed',
    qaNotes: 'Test with 1 member, 50 members, 500 members. Test search and filter.',
    technicalNotes: 'GET /api/workspace/members?search=&role=. Pagination recommended for >50 members.',
    openQuestions: [],
    readinessScore: {
      total: 87,
      clarity: 17,
      acceptanceCriteria: 18,
      businessAlignment: 13,
      technicalFeasibility: 13,
      testability: 9,
      edgeCasesErrorHandling: 8,
      dependenciesDesignLocalization: 9,
      label: 'Minor review needed'
    },
    warnings: [
      { id: 'w5', type: 'missing-localization', message: 'Date format localization not specified in acceptance criteria', severity: 'info' }
    ],
    reviewStatus: 'approved',
    developerReview: {
      status: 'approved',
      comment: 'Straightforward. Add pagination spec to tech notes before cutting the ticket.',
      reviewerName: 'Jordan L.',
      timestamp: '2024-01-15T16:00:00Z',
      pmRevisionStatus: 'resolved'
    }
  },
  {
    id: 'TAM-009',
    epicId: 'epic-3',
    sessionId: 'session-1',
    title: 'Remove team member',
    userStory: 'As an Admin, I want to remove a team member, so that they immediately lose access to the workspace.',
    description: 'Admin can remove any member (except themselves if they are the last Admin) from the Members list. Removal is confirmed via a dialog, then executes: deactivates workspace membership, invalidates all active sessions for that user, sends a notification email.',
    acceptanceCriteria: [
      'Admin sees "Remove" action for each member (not available for themselves).',
      'Confirmation dialog shows member name and role before removal.',
      'Upon confirmation, member is removed from workspace immediately.',
      'Member\'s active sessions are invalidated within 2 seconds.',
      'Removed member sees "Access revoked" message on next request.',
      'Removal is logged in the audit log with admin name and timestamp.',
    ],
    priority: 'P0',
    labels: ['Security', 'Admin'],
    components: ['Frontend', 'Backend', 'Auth'],
    dependencies: ['Session management service', 'TAM-008'],
    edgeCases: [
      'Admin tries to remove themselves — block if last admin, warn otherwise.',
      'Member removed while in active session — invalidate within 2 seconds.',
    ],
    errorHandling: 'Removal API failure: Show error toast, do not update UI. Session invalidation failure: Log error, flag for manual review.',
    localizationNotes: 'Confirmation dialog and notification email localized.',
    designNotes: 'Destructive confirmation dialog (red/danger styling). Show member name prominently in dialog.',
    analyticsNotes: 'Track: member_removed (removed_user_role)',
    qaNotes: 'Test session invalidation timing. Test last-admin protection. Test concurrent session handling.',
    technicalNotes: 'DELETE /api/workspace/members/:id. Must call session-invalidation service synchronously. Audit log: INSERT before DELETE commits.',
    openQuestions: ['Should a notification email be sent to the removed member? If so, what does it say?'],
    readinessScore: {
      total: 79,
      clarity: 16,
      acceptanceCriteria: 17,
      businessAlignment: 13,
      technicalFeasibility: 12,
      testability: 8,
      edgeCasesErrorHandling: 7,
      dependenciesDesignLocalization: 6,
      label: 'Minor review needed'
    },
    warnings: [
      { id: 'w6', type: 'open-question', message: 'Notification email spec is an open question — unresolved', severity: 'warning' }
    ],
    reviewStatus: 'needs-clarification',
    developerReview: {
      status: 'needs-clarification',
      comment: 'Need to confirm: is session invalidation via JWT blacklist or refresh token revocation? The 2-second SLA implies active session detection which needs infrastructure decision.',
      reviewerName: 'Sasha K.',
      timestamp: '2024-01-15T16:30:00Z',
      pmRevisionStatus: 'in-progress'
    }
  },
  {
    id: 'TAM-010',
    epicId: 'epic-3',
    sessionId: 'session-1',
    title: 'Access change audit log',
    userStory: 'As an Admin, I want to see an audit log of all access changes, so that I can track who invited or removed whom.',
    description: 'An audit log page or tab showing all access-related events: invitations sent/accepted/revoked, role changes, and member removals. Filterable by event type, date range, and actor.',
    acceptanceCriteria: [
      'Audit log shows: timestamp, actor (admin name), event type, target (email/name), details.',
      'Filter by event type: invite, accept, revoke, role change, removal.',
      'Filter by date range.',
      'Log is read-only — no modification.',
      'Log retains 12 months of history.',
    ],
    priority: 'P2',
    labels: ['Admin', 'Compliance'],
    components: ['Frontend', 'Backend'],
    dependencies: ['TAM-009'],
    edgeCases: ['Large audit log (>10k events) — paginate with cursor-based pagination.'],
    errorHandling: 'If log fails to load, show error with retry.',
    localizationNotes: 'Dates and event descriptions localized.',
    designNotes: 'Read-only data table. Event type shown as badge. Export to CSV option.',
    analyticsNotes: '',
    qaNotes: 'Test filter combinations. Test pagination with large datasets. Verify retention policy.',
    technicalNotes: 'GET /api/workspace/audit-log?type=&from=&to=&cursor=. Append-only audit_log table.',
    openQuestions: [],
    readinessScore: {
      total: 82,
      clarity: 17,
      acceptanceCriteria: 16,
      businessAlignment: 12,
      technicalFeasibility: 13,
      testability: 8,
      edgeCasesErrorHandling: 8,
      dependenciesDesignLocalization: 8,
      label: 'Minor review needed'
    },
    warnings: [],
    reviewStatus: 'pending'
  },
  // Epic 4: Invitation Lifecycle & Error Handling
  {
    id: 'TAM-011',
    epicId: 'epic-4',
    sessionId: 'session-1',
    title: 'Handle expired invitation token',
    userStory: 'As an invited user, I want to see a clear message when my invitation has expired, so that I know how to get a new one.',
    description: 'When an invitee clicks an expired link, the acceptance page shows a clear expiry message with instructions and a "Request new invitation" CTA that notifies the workspace admin.',
    acceptanceCriteria: [
      'Expired token shows a clear "Invitation expired" page with expiry date.',
      '"Request new link" button sends a notification to the workspace admin.',
      'Admin receives in-app notification and email with one-click resend option.',
      'Invitee sees a confirmation: "We\'ve notified your admin. Expect a new link shortly."',
    ],
    priority: 'P1',
    labels: ['UX', 'Invitation'],
    components: ['Frontend', 'Backend'],
    dependencies: ['TAM-001'],
    edgeCases: ['Admin account is deactivated — route request to another admin or support.'],
    errorHandling: 'Notification send failure: Log error, still show confirmation to invitee.',
    localizationNotes: 'Expiry page fully localized.',
    designNotes: 'Friendly, non-technical error page. Workspace branding. Clear CTA. Mobile-optimized.',
    analyticsNotes: 'Track: invitation_expired_page_viewed, new_link_requested',
    qaNotes: 'Test with tokens expired by: time, manual revocation, already accepted.',
    technicalNotes: 'Token expiry check: compare expires_at to NOW(). Notification: in-app + email via SendGrid.',
    openQuestions: [],
    readinessScore: {
      total: 85,
      clarity: 17,
      acceptanceCriteria: 17,
      businessAlignment: 13,
      technicalFeasibility: 13,
      testability: 9,
      edgeCasesErrorHandling: 8,
      dependenciesDesignLocalization: 8,
      label: 'Minor review needed'
    },
    warnings: [],
    reviewStatus: 'pending'
  },
  {
    id: 'TAM-012',
    epicId: 'epic-4',
    sessionId: 'session-1',
    title: 'Rate limit invitation sending',
    userStory: 'As the system, I want to limit how many invitations an admin can send per hour, so that we protect SendGrid reputation and prevent abuse.',
    description: 'Server-side rate limiting on the invitation endpoint: 50 invitations per admin per hour. When the limit is hit, the API returns a 429 with a Retry-After header. The UI shows a clear rate limit message with the reset time.',
    acceptanceCriteria: [
      'Invitation endpoint returns 429 after 50 invitations per admin per hour.',
      'UI shows: "You\'ve reached the invitation limit (50/hour). Try again at [time]."',
      'Rate limit counter resets after 60 minutes.',
      'Rate limit is per admin (not per workspace).',
      'Rate limit events are logged for abuse detection.',
    ],
    priority: 'P1',
    labels: ['Security', 'API'],
    components: ['Backend'],
    dependencies: ['TAM-001'],
    edgeCases: ['Distributed rate limiting across multiple API instances — must use Redis, not in-memory.'],
    errorHandling: '429 response: UI shows friendly rate limit message. Include Retry-After in API response.',
    localizationNotes: 'Rate limit message localized with dynamic time remaining.',
    designNotes: 'Toast notification with warning styling. Include reset time prominently.',
    analyticsNotes: 'Track: invitation_rate_limit_hit (admin_id)',
    qaNotes: 'Test boundary at exactly 50. Test that 51st request is blocked. Test reset after 60 minutes.',
    technicalNotes: 'Redis-based sliding window rate limiter. Key: rate_limit:invitations:{admin_id}. TTL: 3600s.',
    openQuestions: [],
    readinessScore: {
      total: 88,
      clarity: 18,
      acceptanceCriteria: 17,
      businessAlignment: 13,
      technicalFeasibility: 14,
      testability: 9,
      edgeCasesErrorHandling: 9,
      dependenciesDesignLocalization: 8,
      label: 'Minor review needed'
    },
    warnings: [
      { id: 'w7', type: 'technical-dependency', message: 'Redis dependency not mentioned in known constraints', severity: 'info' }
    ],
    reviewStatus: 'approved',
    developerReview: {
      status: 'approved',
      comment: 'Good. Confirming we use Redis sliding window (not fixed window). Story is solid.',
      reviewerName: 'Jordan L.',
      timestamp: '2024-01-15T17:00:00Z',
      pmRevisionStatus: 'resolved'
    }
  },
];

export const mockExportPackages: ExportPackage[] = [
  {
    id: 'exp-1',
    sessionId: 'session-1',
    sessionName: 'Team Access Management',
    date: '2024-01-15',
    epicCount: 4,
    storyCount: 12,
    avgReadiness: 84,
    format: 'markdown',
    status: 'complete'
  },
  {
    id: 'exp-2',
    sessionId: 'session-2',
    sessionName: 'Subscription Cancellation Flow',
    date: '2024-01-14',
    epicCount: 3,
    storyCount: 9,
    avgReadiness: 71,
    format: 'json',
    status: 'partial'
  },
  {
    id: 'exp-3',
    sessionId: 'session-1',
    sessionName: 'Team Access Management',
    date: '2024-01-12',
    epicCount: 4,
    storyCount: 8,
    avgReadiness: 76,
    format: 'csv',
    status: 'complete'
  },
  {
    id: 'exp-4',
    sessionId: 'session-4',
    sessionName: 'Admin Reporting Dashboard',
    date: '2024-01-11',
    epicCount: 2,
    storyCount: 6,
    avgReadiness: 63,
    format: 'markdown',
    status: 'draft'
  },
  {
    id: 'exp-5',
    sessionId: 'session-3',
    sessionName: 'Multi-language Checkout',
    date: '2024-01-10',
    epicCount: 3,
    storyCount: 11,
    avgReadiness: 79,
    format: 'json',
    status: 'complete'
  },
];
